package com.madania.management.config.seeder;

import com.madania.management.entity.PackageType;
import com.madania.management.entity.Patient;
import com.madania.management.entity.Therapist;
import com.madania.management.entity.TherapyPackage;
import com.madania.management.entity.TherapySession;
import com.madania.management.enums.Role;
import com.madania.management.repository.PackageTypeRepository;
import com.madania.management.repository.TherapyPackageRepository;
import com.madania.management.repository.UserRepository;
import com.madania.management.service.PatientService;
import com.madania.management.service.TherapistService;
import com.madania.management.service.TherapyPackageService;
import com.madania.management.service.TherapySessionService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Comparator;
import java.util.List;
import java.util.UUID;

/**
 * Seeds 8 demo therapy packages across the 6 demo patients:
 * - 2 packages (Kevin Santoso's first, Dimas Rahayu's first) start far
 *   enough in the past that every one of their sessions has already
 *   happened, so they naturally settle into PackageStatus.COMPLETED.
 * - 6 packages start recently enough that some sessions are already in
 *   the past and some are still ahead, so they stay PackageStatus.ACTIVE
 *   with a realistic mix of COMPLETED and SCHEDULED sessions on the
 *   calendar (e.g. yesterday's session completed, tomorrow's scheduled).
 * <p>
 * Every package here starts on a different calendar date. Sessions are
 * generated by TherapyPackageService exactly as they would be through the
 * UI; afterwards, any session whose start time has already passed is
 * marked COMPLETED via TherapySessionService.completeSession - the same
 * path a therapist uses in the app - so completedSessions/status stay
 * consistent with the same business rules the app itself enforces.
 */
@Component
@Order(5)
@RequiredArgsConstructor
@Slf4j
public class TherapyPackageSeeder implements CommandLineRunner {

    private final TherapyPackageService packageService;
    private final TherapySessionService sessionService;
    private final TherapyPackageRepository packageRepository;
    private final PackageTypeRepository packageTypeRepository;
    private final PatientService patientService;
    private final TherapistService therapistService;
    private final UserRepository userRepository;

    private record PackageSeed(String patientName, String therapistEmail, String packageTypeName,
                                List<DayOfWeek> days, LocalTime time, long startedDaysAgo, String notes) {
    }

    @Override
    public void run(String... args) {
        if (!packageRepository.findAll().isEmpty()) {
            return;
        }

        // Each patient's diagnosis (already seeded on Patient) is reused as
        // this package's diagnosis, so what the mentor asked for - diagnosis
        // recorded before/at package creation - holds for seeded data too.
        List<PackageSeed> seeds = List.of(
                new PackageSeed("Kevin Santoso", "nadia.putri@madania.com", "Paket Ringan",
                        List.of(DayOfWeek.MONDAY, DayOfWeek.THURSDAY), LocalTime.of(9, 0), 70,
                        "Paket pertama Kevin, fokus pada manajemen atensi dasar."),
                new PackageSeed("Dimas Rahayu", "amelia.wijaya@madania.com", "Paket Reguler",
                        List.of(DayOfWeek.MONDAY, DayOfWeek.WEDNESDAY, DayOfWeek.FRIDAY), LocalTime.of(13, 0), 77,
                        "Paket pertama Dimas, membangun rutinitas terapi ABA."),
                new PackageSeed("Kevin Santoso", "nadia.putri@madania.com", "Paket Reguler",
                        List.of(DayOfWeek.MONDAY, DayOfWeek.WEDNESDAY, DayOfWeek.FRIDAY), LocalTime.of(9, 0), 15,
                        "Lanjutan Kevin setelah paket pertama, intensitas ditingkatkan."),
                new PackageSeed("Putri Rahayu", "nadia.putri@madania.com", "Paket Ringan",
                        List.of(DayOfWeek.TUESDAY, DayOfWeek.THURSDAY), LocalTime.of(10, 0), 9,
                        "Paket pertama Putri."),
                new PackageSeed("Dimas Rahayu", "amelia.wijaya@madania.com", "Paket Reguler",
                        List.of(DayOfWeek.MONDAY, DayOfWeek.WEDNESDAY, DayOfWeek.FRIDAY), LocalTime.of(14, 0), 17,
                        "Lanjutan Dimas setelah paket pertama."),
                new PackageSeed("Nayla Lestari", "amelia.wijaya@madania.com", "Paket Ringan",
                        List.of(DayOfWeek.TUESDAY, DayOfWeek.THURSDAY), LocalTime.of(11, 0), 11,
                        "Paket pertama Nayla."),
                new PackageSeed("Clara Santoso", "rizky.hidayat@madania.com", "Paket Ringan",
                        List.of(DayOfWeek.MONDAY, DayOfWeek.WEDNESDAY), LocalTime.of(9, 0), 22,
                        "Paket pertama Clara."),
                new PackageSeed("Fajar Fauzi", "rizky.hidayat@madania.com", "Paket Reguler",
                        List.of(DayOfWeek.TUESDAY, DayOfWeek.THURSDAY, DayOfWeek.FRIDAY), LocalTime.of(10, 0), 19,
                        "Paket pertama Fajar.")
        );

        UUID createdByUserId = userRepository.findByRole(Role.ADMIN).stream().findFirst()
                .orElseThrow(() -> new RuntimeException("Seeder error: no admin user found to attribute packages to."))
                .getId();

        int completedCount = 0;
        int ongoingCount = 0;

        for (PackageSeed seed : seeds) {
            Patient patient = patientService.getAllPatients().stream()
                    .filter(p -> p.getFullName().equals(seed.patientName()))
                    .findFirst()
                    .orElseThrow(() -> new RuntimeException("Seeder error: patient not found: " + seed.patientName()));

            Therapist therapist = therapistService.getTherapistByUserId(
                    userRepository.findByEmail(seed.therapistEmail())
                            .orElseThrow(() -> new RuntimeException(
                                    "Seeder error: therapist user not found: " + seed.therapistEmail()))
                            .getId());

            PackageType packageType = packageTypeRepository.findByName(seed.packageTypeName())
                    .orElseThrow(() -> new RuntimeException(
                            "Seeder error: package type not found: " + seed.packageTypeName()));

            LocalDate startDate = LocalDate.now().minusDays(seed.startedDaysAgo());

            TherapyPackage created = packageService.createPackage(
                    patient.getId(), therapist.getId(), createdByUserId, packageType.getId(),
                    startDate, seed.time(), seed.days(), seed.notes(), patient.getDiagnosis(), null);

            if (settlePastSessions(created)) {
                completedCount++;
            } else {
                ongoingCount++;
            }
        }

        log.info("Seeded {} demo therapy packages ({} completed, {} ongoing).",
                seeds.size(), completedCount, ongoingCount);
    }

    /**
     * Marks every session that has already started as COMPLETED, in
     * chronological order, via TherapySessionService.completeSession - the
     * same path the therapist UI uses - so completedSessions and package
     * status update exactly as they would through real use. Returns true if
     * every session in the package was already in the past (i.e. the
     * package is now fully completed).
     */
    private boolean settlePastSessions(TherapyPackage therapyPackage) {
        List<TherapySession> sessions = sessionService.getSessionsByTherapyPackageId(therapyPackage.getId()).stream()
                .sorted(Comparator.comparing(TherapySession::getStartTime))
                .toList();

        LocalDateTime now = LocalDateTime.now();
        int completed = 0;

        for (TherapySession session : sessions) {
            if (session.getStartTime().isBefore(now)) {
                sessionService.completeSession(session.getId());
                completed++;
            }
        }

        return completed == sessions.size();
    }
}
